eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.106.251:8761/eureka/
      
server:
  port: 8765
  
spring:
  application:
    name: eshop-datasync-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://106.13.106.251:3306/eshop
    username: root
    password: Abcd1234%
  rabbitmq:
    host: 106.13.114.54
    port: 5672
    username: rabbitadmin  
    password: 123456